version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - api_metacritic_game

  phpmyadmin:
    image: phpmyadmin:latest
    networks:
      - api_metacritic_game
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - db

  api:
    build: . 
    networks:
      - api_metacritic_game
    environment:
      DATABASE_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - db
      - phpmyadmin

volumes:
  db_data: {}

networks:
  api_metacritic_game:
    driver: bridge