version: '3.8'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 

  api:
    depends_on:
      - db
      - phpmyadmin
    build: . 
    links:
      - "db:metaCritic"
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: db

volumes:
  db_data: {}