name: Node.JS Analyse
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    analyse:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: Run Audit
              working-directory: ./TP3/api_metacritic_game
              run: npm audit