name: Docker Build Node.JS
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Docker Build
              working-directory: ./TP3/api_metacritic_game
              run: docker build .